### ISSUE TITLE
<script setup> by default?

### ISSUE THREAD

**Issue by dy** [WebReflection/uce-template#1]
What was the reason for not making script a direct _setup_, as in [the proposal](https://github.com/vuejs/rfcs/blob/sfc-improvements/active-rfcs/0000-sfc-script-setup.md)?
If that could also enable `scoped`-like context for the script, uce-template would be invaluable, because refs could be solved with export live bindings:

```html
<template is="uce-template">
  <x-clock>{{ time }}</x-clock>
  <script type="module" scoped>
    export let time = new Date;
    let id
    this.onconnected = e => setInterval(() => time = new Date);
    this.ondisconnected = e => clearInterval(id)
  </script>
</template>
```

**Comment by WebReflection** [comment]
> export live bindings

nope, this ain't gonna work because the module system is CommonJS, not ESM, however, when `setup` is encountered the module might as well be the setup itself so it's a good hint, but the example would be:

```html
  <x-clock></x-clock>
  <template is="uce-template">
    <x-clock>{{time}}</x-clock>
    <script type="module" setup>
      let id = 0;
      export default {
        get time() {
          return (new Date).toISOString();
        }
      };
      this.connected = e => id = setInterval(this.render, 1000 / 30);
      this.disconnected = e => clearInterval(id);
    </script>
  </template>
```

**Comment by WebReflection** [comment]
It's in, v0.2 has this behavior already 👋

**Comment by WebReflection** [comment]
Btw ... *that proposal* is something I haven't read at all ... like ... I've read nothing about *Vue* and I've never used it, so if there are other obvious things I'm missing in here, and these won't bloat the library, I'd be happy to consider other features, thanks!

**Comment by WebReflection** [comment]
P.S. `<script setup="props">` also works now, so that exporting `props = {a: 1, b: 2}` would make these reactive through the element

**Comment by dy** [comment]
Looks awesome, lightning fast response. The context is a great DX I
believe. The concern  I have though is missing vue-like reactivity - to
update clock `this.render` is called (30 times more often than needed),
instead of just setting `this.time = new Date`. Initially I imagined the
scheme `this.props.time` - inspired by your el.props idea (https://ghub.io/element-props) some months
ago - seems intuitive and also react-like, wdyt?

**Comment by dy** [comment]
Or `export default` could be used for exporting observable props / propTypes, as you mentioned:
```html
<x-clock></x-clock>
  <template is="uce-template">
    <x-clock>{{ time }}</x-clock>
    <script type="module" setup>
      // vue-like prop types + observed attributes
      export default { time: Date };

      let id = 0;
      this.onconnected = e => id = setInterval(() => this.time = new Date, 1000);
      this.ondisconnected = e => clearInterval(id);
    </script>
  </template>
```
One interesting case is built-in reactivity without explicit imports. Some components could be used as a store, for example:
```html
<template is="uce-template">
<data-store />
<script type="module" setup>
export default {
  title: String, count: Number
}
</script>
</template>
<data-store id="store"/>

<!-- ...in the DOM -->
<script>
store.title = 'Hello World'
store.count++
</script>
```

**Comment by WebReflection** [comment]
the whole strength of `uhtml` is that you don't care about rendering time, but I don't see anything different from your initial example ... change the interval delay as you like and you're done? Not sure how that would work otherwise.

Regarding props, `<script setup="props">` hint that `props` will be exported and used, and props are reactive already, but you need to still change the `element.time = new Date` whenever you want to see it reflected.

**Comment by dy** [comment]
Hmm, tried your example, getting
```
Uncaught TypeError: Cannot convert undefined or null to object
    at keys (<anonymous>)
    at Ce (uce-template:3)
```

```html
<script src="https://unpkg.com/uce-template"></script>

<x-clock></x-clock>

<template is="uce-template">
  <x-clock>{{time}}</x-clock>
  <script type="module" setup="props">
    let id = 0;
    export default {
        get time() {
          return (new Date).toISOString();
        }
      };
    this.connected = e => id = setInterval(this.render, 1000 / 30);
    this.disconnected = e => clearInterval(id);
  </script>
</template>

```

**Comment by WebReflection** [comment]
please read the documentation around *props*, it's not exclusive ... you have to export a `props` object ... using setup="props"` without providing props is pointless
