### ISSUE TITLE
dependency misconfiguration in v. 0.7.0

### ISSUE THREAD

**Issue by tvardy** [WebReflection/uce-template#11]
After updating from v.0.6.0 to v.0.7.0 I'm getting this error in `npm ls`:

```
npm ERR! missing: async@0.2.6, required by terser@5.7.1
npm ERR! missing: dedent@0.6.0, required by terser@5.7.1
npm ERR! missing: parse5@2.2.3, required by terser@5.7.1
npm ERR! missing: pify@2.3.0, required by terser@5.7.1
npm ERR! missing: strip-bom@2.0.0, required by terser@5.7.1
npm ERR! extraneous: async@0.2.6 [...]/node_modules/terser/node_modules/async
npm ERR! extraneous: dedent@0.6.0 [...]/node_modules/terser/node_modules/dedent
npm ERR! extraneous: parse5@2.2.3 [...]/node_modules/terser/node_modules/parse5
npm ERR! extraneous: pify@2.3.0 [...]/node_modules/terser/node_modules/pify
npm ERR! extraneous: strip-bom@2.0.0 [...]/node_modules/terser/node_modules/strip-bom
```

**Comment by WebReflection** [comment]
This library uses none of those modules though … not sure what I can do for you

**Comment by tvardy** [comment]
I think these are the `html-minifier-terser` or `terser` indirect dependencies...

![Screenshot 2021-07-02 at 10 02 18](https://user-images.githubusercontent.com/694872/124242236-d1c75180-db1c-11eb-8afb-ab09dc6c85f2.png)

**Comment by WebReflection** [comment]
@tvardy I've updated all dependencies and I don't see any error ... is this OK now?

**Comment by tvardy** [comment]
Just checked the `0.7.1` - yeah! the dependency tree is clear now ;)
Taa, mate!

Now I can try if the minification works better than in the `0.6.0` ;)
