### ISSUE TITLE
ESLint parser for `.uce` files

### ISSUE THREAD

**Issue by brettz9** [WebReflection/uce-template#12]
Just a suggestion for the ecosystem...

It'd be awfully handy if one could get an ESLint-comopatible `.uce` file parser. Something along the lines of [`vue-eslint-parser`](https://github.com/vuejs/vue-eslint-parser).

As a bonus, a plugin like [`eslint-plugin-vue`](https://eslint.vuejs.org/user-guide/#usage) could be very useful as well (some of the rules of the latter might even be reusable for such a plugin).

I really don't dare move my code into files that don't provide the safety net of at least JavaScript linting.

**Comment by WebReflection** [comment]
like this? https://webcomponents.dev/edit/BtM0JrRI7aZjvKbgmUWt/src/my-counter.uce?p=stories

**Comment by WebReflection** [comment]
> I really don't dare move my code into files that don't provide the safety net of at least JavaScript linting.

so .. you wouldn't dare writing HTML files? that's all it is here ... but I am not sure this statement means you'll never use uce-template, but if that's the case, feel free to not use it 👋

**Comment by brettz9** [comment]
Oh, apologies, I wasn't clear that the loader could expect something without a `<template>` wrapper. Anyways, my filing an issue was obviously because I otherwise had interest in the package and thought it could be an issue for others if so, and not because I expect anyone to care whether I personally use it or not. Thank you for your explanation.
