### ISSUE TITLE
event props fired at first render...

### ISSUE THREAD

**Issue by tvardy** [WebReflection/uce-template#7]
Hi!
Firstly, maybe I'm doing something wrong 😅  But here's the issue:

Demo commit: https://github.com/tvardy/js-playground/commit/47d709ec52d1f5806afce00354b424a7b3c494cf
(`npm i` + `npm start` and you can see the demo page)

I was playing around with some lightweight and simple state management solutions being able to connect to micro-frontends.

If you look into `clicker-stent.uce` and `clicker-preach.uce` you'd be able to see 3 versions of connecting the store to the component.

- version (a) is dynamically loading the store file using `import()`
- version (b) is using the `resolve` function provided by `uce-template` to load the store
- version (c) does the same but moves the connection to the end of the queue with `setTimeout`

Now, the problem is that the nicest looking version (b) does not work as expected. It fires the `increase` action immediately during the first render and that changes the global state.

I'm not sure why is this happening 🤔

**Comment by tvardy** [comment]
I found out that it **only** happens for `props` option... So the quick solution was to change a bit a structure of the components and change `setup="props"` to just `setup`.

https://github.com/tvardy/js-playground/commit/3d7bacbca66718296f04b18952ef06e4eaa7d178

**Comment by WebReflection** [comment]
Apologies I’ve had fever and felt sick last days, I haven’t managed to check your code.

however, if you found a specific props issue please file a bug with a minimal case and I’ll fix it
